#!/usr/bin/env bash
# install nginx when it listening on port 80

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx start
