#!/usr/bin/env bash

# Update the package list and install Nginx
apt-get -y update
apt-get -y install nginx

# Allow Nginx through the firewall
ufw allow 'Nginx HTTP'

# Set permissions for the web root
chmod -R 755 /var/www/html

# Create an index page with "Hello World"
echo 'Hello World' > /var/www/html/index.html

# Create a new Nginx configuration
new_config="
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    location / {
        try_files \$uri \$uri/ =404;
    }
    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}"

# Create a custom 404 error page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Write the new Nginx configuration
echo "$new_config" > /etc/nginx/sites-available/default

# Start or restart Nginx
if pgrep nginx > /dev/null; then
    service nginx restart
else
    service nginx start
fi;
