#!/usr/bin/env bash
# Install and configure HAproxy on my load balancer

sudo apt-get update
sudo apt-get install haproxy -y

# Configure loadbalancer
sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOT
frontend nadduli-alx-frontend
        bind *:80
	mode http
        default_backend nadduli-alx-backend

backend nadduli-alx-backend
        balance roundrobin
        server 118325-web-01 54.172.81.125:80 check
        server 118325-web-02 52.204.68.184:80 check
EOT

# start the loadbalancer
sudo /etc/init.d/haproxy start

# set HAProxy to start at boot
sudo update-rc.d haproxy defaults

# reload HAProxy configuration
sudo /etc/init.d/haproxy reload
