#!/usr/bin/env bash
# fix nginx web server and start listening on port 80 by creating a symbolic link

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart