#!/usr/bin/env bash
# script to print message

COUNTER=0
while [ $COUNTER -lt 11 ]
do
if [ $COUNTER = 4 ];
then
echo "bad luck"
fi
elif [ $COUNTER = 8 ]
then
echo "good luck"
else
echo "Best School"
fi
((COUNTER++))
done