#!/usr/bin/env bash
# script to print hour and minutes

H=0
M=1
while [ $H -le 12 ];
do
    echo "Hour: "$H
    while [ $M -le 59 ];
    do
	echo $M
	(( M++ ));
    done;
    (( m=1 ))
    (( H++ ));
done;
