#!/usr/bin/env bash
# script to adduser nginx to the configuration file
# kill apache2 service which was listening on port 8080
# configure nginx to start listening on port 8080

pkill -f apache2
chmod 644 /etc/nginx/nginx.conf
sed -i "1i user nginx;" /etc/nginx/nginx.conf
sed -i "s/80/8080/" /etc/nginx/sites-available/default
sudo -u nginx service nginx restart